Setup
Gracetemitope/mv-book-store pull request #1
Opened 2021-08-25 21:27 UTC by Gracetemitope

- Initialized React App
- Set up React Router and React Redux
- Structure project folder using feature folder approach
- Displayed List of Books

2021-08-25 22:09 UTC, Davidosky007 requested changes
## Hi @Gracetemitope 👋, 

Good job so far! 💪 
* The repo looks professional.✔️
* Git/GitHub flow best practices have been followed✔️
* There are no linter errors✔️
* You have descriptive PR✔️

## There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-25 22:09 UTC, Davidosky007 commented on src/components/AddBook.js
> +      <option value="saab">Biography</option>
* Kindly add a button to submit the form the button wouldn't add the book yet, this is just a placeholder for now
* Refer to project sneak peek 
![image](https://user-images.githubusercontent.com/52497246/130869952-82137fe6-3cb5-42e8-85c7-bea8a543a3a0.png)

2021-08-25 22:09 UTC, Davidosky007 commented on README.md
> +
* Add a descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project

2021-08-25 22:09 UTC, Davidosky007 commented on src/components/redux/categories/categories.js
> +    </div>
* Kindly fix your redux folder as it should be inside `src` (src/redux/books/books.js) and not (src/components/redux/books/books.js)

2021-08-25 23:03 UTC, Davidosky007 commented
## Hi @Gracetemitope 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-25 23:06 UTC, merged

2021-08-31 07:51 UTC, Gracetemitope commented
Dear Reviewer, I'm repeating the week. This PR has  been approved previously. I only need to submit the task. Thanks

2021-08-31 08:02 UTC, oxenprogrammer reviewed
Hi @Gracetemitope , 
This project was already approved. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._